### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by andris155** [OpticFusion1/SlimefunReloaded-ColoredEnderChests#1]
<img width="845" alt="Annotation 2019-12-27 145500" src="https://user-images.githubusercontent.com/8324198/71519687-dde3aa80-28b8-11ea-90a5-fb51c183180d.png">

**Comment by OpticFusion1** [comment]
See response here https://github.com/OpticFusion1/SlimefunReloaded-ChestTerminal/issues/1
